version: '3'
services:
  weblate:
    image: weblate/weblate
    ports:
    - 8080:8080
    volumes:
    - weblate-data:/app/data
    - weblate-cache:/app/cache
    env_file:
    - environment-max
    restart: always
    depends_on:
    - database
    - cache
    networks:
      - default
  database:
    image: postgres:15-alpine
    env_file:
    - environment-max
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - default
  cache:
    image: redis:7-alpine
    restart: always
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
    networks:
      - default

volumes:
  weblate-cache: {}
  weblate-data: {}
  postgres-data: {}
  redis-data: {}